/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.NuevaCuenta;

import Vistas.InicioSeccion.inicioSeccionC;
import Vistas.info.InfoC;
import java.awt.Color;

/**
 *
 * @author Emml_
 */
public class CrearCuentaC extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuentaC
     */
    public CrearCuentaC() {
        initComponents();
        CrearCuentaC.this.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTexfieldPH_FielTex1 = new LIB.JTexfieldPH_FielTex();
        jTexfieldPH_FielTex2 = new LIB.JTexfieldPH_FielTex();
        jTexfieldPH_FielTex3 = new LIB.JTexfieldPH_FielTex();
        jTexfieldPH_FielTex4 = new LIB.JTexfieldPH_FielTex();
        jTexfieldPH_FielTex5 = new LIB.JTexfieldPH_FielTex();
        jTexfieldPH_FielTex6 = new LIB.JTexfieldPH_FielTex();
        jTexfieldPH_FielTex7 = new LIB.JTexfieldPH_FielTex();
        jButton1 = new javax.swing.JButton();
        fSGradientPanel1 = new LIB.FSGradientPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Uber");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 210, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Back.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Tengo Auto");
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jCheckBox2.setText("Necesito un auto");
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 130, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Registrate ahora");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, -1));

        jTexfieldPH_FielTex1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTexfieldPH_FielTex1.setPlaceholder("Nombre");
        jPanel2.add(jTexfieldPH_FielTex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 220, -1));

        jTexfieldPH_FielTex2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTexfieldPH_FielTex2.setPlaceholder("Apellidos");
        jPanel2.add(jTexfieldPH_FielTex2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 220, -1));

        jTexfieldPH_FielTex3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTexfieldPH_FielTex3.setPlaceholder("Correo");
        jPanel2.add(jTexfieldPH_FielTex3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, -1));

        jTexfieldPH_FielTex4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTexfieldPH_FielTex4.setPlaceholder("Contraseña");
        jPanel2.add(jTexfieldPH_FielTex4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 220, -1));

        jTexfieldPH_FielTex5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTexfieldPH_FielTex5.setPlaceholder("Numero celular");
        jPanel2.add(jTexfieldPH_FielTex5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 220, -1));

        jTexfieldPH_FielTex6.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTexfieldPH_FielTex6.setPlaceholder("Ciudad");
        jPanel2.add(jTexfieldPH_FielTex6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, -1));

        jTexfieldPH_FielTex7.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTexfieldPH_FielTex7.setPlaceholder("Estado");
        jPanel2.add(jTexfieldPH_FielTex7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 110, -1));

        jButton1.setBackground(new java.awt.Color(18, 18, 18));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Siguiente");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 300, 390));

        fSGradientPanel1.setFSEndColor(new java.awt.Color(18, 18, 18));
        fSGradientPanel1.setFSGradientFocus(100);
        fSGradientPanel1.setFSStartColor(new java.awt.Color(9, 9, 26));
        fSGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/close.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        fSGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        getContentPane().add(fSGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 0, 303, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        inicioSeccionC isc = new inicioSeccionC();
        isc.show();
        
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InfoC ic = new InfoC();
        ic.show();
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuentaC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSGradientPanel fSGradientPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private LIB.JTexfieldPH_FielTex jTexfieldPH_FielTex1;
    private LIB.JTexfieldPH_FielTex jTexfieldPH_FielTex2;
    private LIB.JTexfieldPH_FielTex jTexfieldPH_FielTex3;
    private LIB.JTexfieldPH_FielTex jTexfieldPH_FielTex4;
    private LIB.JTexfieldPH_FielTex jTexfieldPH_FielTex5;
    private LIB.JTexfieldPH_FielTex jTexfieldPH_FielTex6;
    private LIB.JTexfieldPH_FielTex jTexfieldPH_FielTex7;
    // End of variables declaration//GEN-END:variables
}
